### ISSUE TITLE
Unnecessary new byte[] zeroing

### ISSUE THREAD

**Issue by Nucs** [adam-dot-cohen/HyperSerializer#3]
https://github.com/adam-dot-cohen/HyperSerializer/blob/42c6b1c1395539bc4d6d5b0c9a7267fa0e7bb136/HyperSerializer/HyperBinarySerializerExperimental.cs#L22
https://github.com/adam-dot-cohen/HyperSerializer/blob/42c6b1c1395539bc4d6d5b0c9a7267fa0e7bb136/HyperSerializer/HyperBinarySerializerExperimental.cs#L105

The mentioned lines can use (and potentially more) [GC.AllocateUninitializedArray<T>](https://learn.microsoft.com/en-us/dotnet/api/system.gc.allocateuninitializedarray?view=net-6.0)

**Comment by adam-dot-cohen** [comment]
`HyperBinarySerializerExperimental` is and internal class that isn't used for anything and isn't intended for end user consumption.  Is there a reason you're trying to use this class?
