### ISSUE TITLE
There was lost possibility to serialize property of byte array type

### ISSUE THREAD

**Issue by ot-roman-molchanov** [adam-dot-cohen/HyperSerializer#5]
In the HyperSerializer v1.0.15 was possible to serialize the object like that, without lost of ImageBytes array value:
public sealed class ScreenshotContent
{
    public int Width { get; set; }
    public int Height { get; set; }
    public byte[]? ImageBytes { get; set; }
}
var content = new ScreenshotContent
{
    Width = 100,
    Height = 200,
    ImageBytes = new byte[] { 1, 2, 3, 4, 5, 6, 7 }
};
var serializedContent = HyperSerializer<ScreenshotContent>.Serialize(content).ToArray();
Starting from HyperSerializer v1.0.17 this possibility was lost. This property is just ignored now.
Is it possible to return the possibility of byte array serialization?

**Comment by adam-dot-cohen** [comment]
Looking into it.

**Comment by adam-dot-cohen** [comment]
Issue has been resolved.  See link to test class with the code you posted below.

Also, you can continue using `HyperSerializer<T>` as you were or the new non-generic convenience type that I added HyperSerializer (only have to specify type param on Deserialize.

I released a NuGet as well. v1.2

I'll wait to for you to confirm the fix before closing this out.  LMK.

https://github.com/adam-dot-cohen/HyperSerializer/blob/01a7e9da7612b96fe6fbfa8569df604bcc8c8129/HyperSerializer.Test/SerializerTests.cs#L274C40-L274C40

**Comment by ot-roman-molchanov** [comment]
I confirm the fix. Good job! Thanks a lot for fast response and fix!
