### ISSUE TITLE
Dump Mode - for Debugging

### ISSUE THREAD

**Issue by najak3d** [adam-dot-cohen/HyperSerializer#7]
Would be nice to be able to set compiler directive, which supplements the binary serialization with a Debug Dump to file, giving the details of what was serialized (in readable text form).  So if/when things go wrong, we can see what was "Written/Read" to/from the binary stream.   This debug dump would tell you member names, types, byte-size, and values.   Something like:

Name<string>[11]: "Adam Cohen"
Age<Int32>[4]: 869
Birthdate<DateTime>[8]: Dec 25th, 1154
Velocity3D<Vector3>[12]:
      X<float>[4]:  1.432
      Y<float>[4]:  0
      Z<float>[4]:  -3912.43

Something like that..  Would save us tons of time, when it comes to debugging when things go wrong.

**Comment by adam-dot-cohen** [comment]
Support added set `HyperSerializerSettings.WriteProxyToConsoleOutput = true` before calling the serializer to write the output to the console.
